 # spring configuration
spring:
   application:
      name: jblog6
   

   # devtools - live reload
   devtools:
      livereload:
         enabled: true
         
   thymeleaf:
      check-template-location: true
      mode: HTML	
      prefix: classpath:templates/
      suffix: .html
      encoding: UTF-8
      view-names: th/*
      cache: false
         
   # aop
   aop:
      auto: true
      proxy-target-class: true
         
   # mvc
   mvc:
      throw-exception-if-no-handler-found: true
      # static-path-pattern: /assets/**
      # view:
        # prefix: /WEB-INF/views/
         # suffix: .jsp
   
   # web
   web:
     resources:
         static-locations: file:/jblog-uploads/, classpath:assets/
   
   # message resources(internationalization, i18n)
   messages:
      basename: messages/message
      encoding: utf-8
      always-use-message-format: true
   
   # multipart resolver
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 10MB

   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.212:3306/jblog?charset=utf8
      username: jblog
      password: jblog
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
         
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
          
# server configuration
server:
   port: 8088
   servlet:
      context-path: /jblog6
      encoding:
         charset: utf-8
         enabled: true
   error:
      whitelabel:
         enabled: false
      path: /error
         
         
         
# logging
logging:
   config: classpath:logback.xml
